Repository jumpserver/jumpserver, pull requests merged in 2020-07, with the labels that each got.

#4282 merge: Merge to master from branch dev
  .github/ISSUE_TEMPLATE.md
  .github/release-config.yml
  .github/workflows/release-drafter.yml
  .gitignore
  README.md
  apps/assets/api/gathered_user.py
  apps/assets/api/system_user.py
  apps/audits/api.py
  apps/common/drf/renders/csv.py
  apps/common/http.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/custom.py
  apps/jumpserver/views/index.py
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
  apps/users/utils.py
  apps/users/views/profile/otp.py
  apps/users/views/profile/password.py
  build.sh
  utils/build.sh
  utils/build_docker.sh
  utils/example_api.py
Labels: 无需处理

#4280 merge: Merge to master from branch dev
  apps/assets/api/asset.py
  apps/assets/filters.py
  apps/assets/migrations/0050_auto_20200702_1602.py
  apps/assets/models/asset.py
  apps/assets/models/domain.py
  apps/assets/models/node.py
  apps/assets/serializers/asset.py
  apps/assets/tasks/asset_user_connectivity.py
  apps/assets/tasks/system_user_connectivity.py
  apps/audits/migrations/0009_auto_20200624_1654.py
  apps/audits/models.py
  apps/audits/serializers.py
  apps/authentication/errors.py
  apps/authentication/forms.py
  apps/authentication/templates/authentication/login.html
  apps/authentication/templates/authentication/xpack_login.html
  apps/authentication/tests.py
  apps/authentication/utils.py
  apps/authentication/views/login.py
  apps/common/db/__init__.py
  apps/common/db/aggregates.py
  apps/common/drf/api.py
  apps/common/drf/parsers/csv.py
  apps/common/drf/serializers.py
  apps/common/exceptions.py
  apps/common/mixins/api.py
  apps/jumpserver/conf.py
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
  apps/orgs/api.py
  apps/static/js/plugins/jsencrypt/jsencrypt.min.js
  apps/tickets/api/__init__.py
  apps/tickets/api/request_asset_perm.py
  apps/tickets/exceptions.py
  apps/tickets/models/ticket.py
  apps/tickets/permissions.py
  apps/tickets/serializers/__init__.py
  apps/tickets/serializers/request_asset_perm.py
  apps/tickets/urls/api_urls.py
  apps/users/api/profile.py
  apps/users/api/user.py
  apps/users/filters.py
  apps/users/serializers/group.py
  apps/users/serializers/user.py
Labels: 无需处理

#4374 ci(github): 添加通用action
  .github/workflows/jms-generic-action-handler.yml
Labels: 无需处理

#4375 ci(github): 添加通用action
  .github/workflows/jms-generic-action-handler.yml
Labels: 无需处理

#4376 ci(github): 添加通用action
  .github/workflows/jms-generic-action-handler.yml
Labels: 无需处理

#4377 ci(github): 添加通用action
  .github/workflows/jms-generic-action-handler.yml
Labels: 无需处理

#4378 feat(ops): 项目启动时，清除指定的celery定时任务;添加获取celery定时任务的函数
  apps/ops/celery/utils.py
  apps/ops/tasks.py
Labels: 新功能

#4401 fix(perms): 修复perms api UserPermissionMixin 中 kwargs 参数传递（未发现引出其他问题）
  apps/perms/api/mixin.py
Labels: fix

#4380 refactor(orgs): 重构组织表结构
  apps/audits/api.py
  apps/audits/filters.py
  apps/audits/models.py
  apps/common/const/choices.py
  apps/common/db/aggregates.py
  apps/common/db/models.py
  apps/common/drf/fields.py
  apps/jumpserver/api.py
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
  apps/orgs/api.py
  apps/orgs/migrations/0004_organizationmember.py
  apps/orgs/migrations/0005_auto_20200721_1937.py
  apps/orgs/migrations/0006_auto_20200721_1937.py
  apps/orgs/models.py
  apps/orgs/serializers.py
  apps/orgs/signals_handler.py
  apps/orgs/tests.py
  apps/orgs/urls/api_urls.py
  apps/users/api/mixins.py
  apps/users/api/user.py
  apps/users/filters.py
  apps/users/forms/user.py
  apps/users/models/user.py
  apps/users/serializers/user.py
  apps/users/templates/users/user_detail.html
  apps/users/utils.py
Labels: 优化
