Repository jumpserver/jumpserver, pull requests merged in 2020-11, with the labels that each got.

#4912 fix(audits): sso 登录日志没有 type
  apps/authentication/api/sso.py
Labels: fix

#4991 fix(system_user): 修复更新系统用户时ad_domain字段为空提交失败的问题
  apps/assets/serializers/system_user.py
Labels: 类型:bug

#5032 fix(assets): 修复获取org_root的问题
  apps/assets/models/node.py
Labels: 类型:bug

#5034 fix(perms): nodes-with-assets 接口添加刷新重构树
  apps/perms/api/asset/user_permission/user_permission_nodes_with_assets.py
Labels: 类型:bug

#5076 fix(perms): 在动态用户所绑定的授权规则中，如授权给用户组，当用户组增加成员后，动态系统用户下没有相应增加用户，因此也不会自动推送
  apps/perms/signals_handler.py
Labels: 类型:bug

#5077 fix(perms): 在动态用户所绑定的授权规则中，如授权给用户组，当用户组增加成员后，动态系统用户下没有相应增加用户，因此也不会自动推送
  apps/perms/signals_handler.py
Labels: 类型:bug

#5084 refactor(perms): 在动态用户所绑定的授权规则中，如授权给用户组，当用户组增加成员后，动态系统用户下没有相应增加用户，因此也…
  apps/perms/signals_handler.py
  apps/users/signals_handler.py
Labels: 类型:优化
