Repository jumpserver/jumpserver, pull requests merged in 2020-09, with the labels that each got.

#4566 feat(README): 添加企业版试用链接
  README.md
Labels: 新功能

#4611 Dev
  Dockerfile
  README.md
  apps/audits/tasks.py
  apps/authentication/signals_handlers.py
  apps/common/fields/model.py
  apps/common/tasks.py
  apps/common/utils/crypto.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/custom.py
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
  apps/settings/api.py
  apps/settings/tasks/ldap.py
  apps/tickets/migrations/0004_ticket_comment.py
  apps/tickets/models/ticket.py
  apps/tickets/serializers/request_asset_perm.py
  apps/users/api/user.py
  apps/users/models/user.py
  apps/users/serializers/user.py
  config_example.yml
Labels: 无需处理

#4626 feat(authentication):登录表单仅提交时加密
  apps/authentication/templates/authentication/login.html
  apps/authentication/templates/authentication/xpack_login.html
Labels: 新功能

#4630 feat(authentication):将cas认证通过的登录日志记录到系统
  apps/authentication/signals_handlers.py
Labels: 新功能

#4665 fix(command): 修复命令导出选中项问题
  apps/common/drf/filters.py
  apps/terminal/api/command.py
Labels: fix

#4667 fix(command): 修复命令导出选中项问题
  apps/terminal/api/command.py
Labels: fix
