Repository jumpserver/jumpserver, pull requests merged in 2020-12, with the labels that each got.

#5163 fix: 添加迁移文件: Node ordering
  apps/assets/migrations/0064_auto_20201203_1100.py
Labels: 类型:bug

#5182 feat: 取消资产配置相关字段只读模式
  apps/assets/serializers/asset.py
Labels: 类型:新功能

#5183 feat: 用户授权应用树按组织节点进行区分
  apps/applications/api/mixin.py
  apps/orgs/mixins/models.py
  apps/orgs/utils.py
  apps/perms/api/application/user_permission/user_permission_applications.py
  apps/perms/api/asset/user_permission/user_permission_nodes_with_assets.py
  apps/perms/urls/asset_permission.py
Labels: 类型:新功能

#5236 Pr@dev@fix node error log
  apps/assets/models/node.py
Labels: 类型:bug

#5256 chore: Merge master from dev
  apps/assets/models/node.py
  apps/audits/migrations/0011_userloginlog_backend.py
  apps/jumpserver/urls.py
  apps/jumpserver/views/swagger.py
  apps/orgs/signals_handler.py
  apps/terminal/api/component.py
  apps/terminal/migrations/0030_terminal_type.py
  apps/terminal/models/terminal.py
  apps/terminal/serializers_v2/terminal.py
  apps/terminal/utils.py
  apps/tickets/serializers/request_asset_perm.py
Labels: 结果:无需处理

#5292 fix: 修改系统监控问题
  apps/terminal/utils.py
Labels: 类型:bug

#5293 fix: 修改系统监控问题
  apps/terminal/utils.py
Labels: 类型:bug

#5295 fix: 修复命令列表过滤字段文案`会话ID`
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
  apps/terminal/backends/command/serializers.py
Labels: 类型:bug
