Repository jumpserver/jumpserver, pull requests merged in 2021-09, with the labels that each got.

#6747 feat: 添加 GCP 同步依赖
  requirements/requirements.txt
Labels: 类型:新功能

#6768 feat: 支持 Session 会话共享
  apps/jumpserver/conf.py
  apps/jumpserver/settings/custom.py
  apps/settings/api/common.py
  apps/settings/serializers/settings.py
  apps/terminal/api/__init__.py
  apps/terminal/api/sharing.py
  apps/terminal/migrations/0040_sessionjoinrecord_sessionsharing.py
  apps/terminal/models/__init__.py
  apps/terminal/models/sharing.py
  apps/terminal/serializers/__init__.py
  apps/terminal/serializers/sharing.py
  apps/terminal/urls/api_urls.py
Labels: 类型:新功能

#6709 feat: 改密计划支持数据库改密
  Dockerfile
  apps/applications/api/account.py
  apps/applications/api/application.py
  apps/applications/migrations/0010_appaccount_historicalappaccount.py
  apps/applications/migrations/0011_auto_20210826_1759.py
  apps/applications/models/__init__.py
  apps/applications/models/account.py
  apps/applications/serializers/application.py
  apps/assets/api/system_user_relation.py
  apps/assets/models/authbook.py
  apps/assets/models/user.py
  apps/assets/serializers/system_user.py
  apps/common/management/commands/services/services/base.py
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
  apps/perms/api/application/user_group_permission.py
  apps/perms/api/application/user_permission/user_permission_applications.py
  apps/perms/serializers/application/user_permission.py
  apps/perms/signals_handler/__init__.py
  apps/perms/signals_handler/app_permission.py
  apps/perms/signals_handler/asset_permission.py
  requirements/requirements.txt
Labels: 类型:新功能

#6784 perf: Update README
  README.md
Labels: 类型:优化

#6905 fix: 添加 pg 依赖包
  requirements/deb_buster_requirements.txt
  requirements/deb_requirements.txt
Labels: 类型:bug
