Repository jumpserver/jumpserver, pull requests merged in 2022-08, with the labels that each got.

#8686 feat: 认证方式支持OAuth2.0协议
  apps/authentication/backends/oauth2/__init__.py
  apps/authentication/backends/oauth2/backends.py
  apps/authentication/backends/oauth2/signals.py
  apps/authentication/backends/oauth2/urls.py
  apps/authentication/backends/oauth2/views.py
  apps/authentication/backends/oidc/backends.py
  apps/authentication/backends/oidc/utils.py
  apps/authentication/backends/oidc/views.py
  apps/authentication/backends/saml2/backends.py
  apps/authentication/signal_handlers.py
  apps/authentication/urls/view_urls.py
  apps/authentication/utils.py
  apps/authentication/views/login.py
  apps/common/utils/common.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/auth.py
  apps/locale/ja/LC_MESSAGES/django.mo
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
  apps/settings/api/settings.py
  apps/settings/models.py
  apps/settings/serializers/auth/__init__.py
  apps/settings/serializers/auth/oauth2.py
  apps/static/img/login_oauth2_logo.png
  apps/users/models/user.py
  apps/users/signal_handlers.py
  apps/users/utils.py
Labels: 类型:新功能

#8698 perf: update readme
  README.md
Labels: 类型:优化

#8591 feat: 支持CMPPv2.0协议短信网关
  apps/common/sdk/sms/base.py
  apps/common/sdk/sms/cmpp2.py
  apps/common/sdk/sms/endpoint.py
  apps/jumpserver/conf.py
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.po
  apps/settings/api/__init__.py
  apps/settings/api/alibaba_sms.py
  apps/settings/api/settings.py
  apps/settings/api/sms.py
  apps/settings/api/tencent_sms.py
  apps/settings/serializers/auth/sms.py
  apps/settings/serializers/settings.py
  apps/settings/urls/api_urls.py
Labels: 类型:新功能

#8717 perf: 补充cmpp2翻译及部分报错提示
  apps/common/sdk/sms/cmpp2.py
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.po
  apps/settings/api/sms.py
  apps/settings/serializers/auth/sms.py
Labels: 类型:优化

#8780 Revert "fix: 修复服务端渲染请求缺少csrf token 问题"
  apps/authentication/templates/authentication/login_wait_confirm.html
  apps/static/js/jumpserver.js
Labels: 类型:bug

#8774 feat: MongoDB支持连接SSL类型
  apps/applications/serializers/attrs/application_category/db.py
Labels: 类型:新功能
