Repository jumpserver/jumpserver, pull requests merged in 2022-09, with the labels that each got.

#8816 feat: 支持OAuth2协议自定义注销功能
  apps/authentication/backends/oauth2/urls.py
  apps/authentication/backends/oauth2/views.py
  apps/authentication/backends/saml2/views.py
  apps/authentication/views/login.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/auth.py
  apps/jumpserver/settings/base.py
  apps/settings/serializers/auth/oauth2.py
Labels: 类型:新功能

#8837 feat: 支持MFA可配置华为云平台短信对接
  apps/common/sdk/sms/endpoint.py
  apps/common/sdk/sms/huawei.py
  apps/jumpserver/conf.py
  apps/settings/api/settings.py
  apps/settings/api/sms.py
  apps/settings/serializers/auth/sms.py
Labels: 类型:新功能

#8797 feat: 改密计划支持MongoDB改密
  requirements/requirements.txt
Labels: 类型:新功能

#8839 perf: 支持连接开启ssl且自签证书的Redis/MongoDB
  apps/applications/serializers/attrs/application_category/db.py
Labels: 类型:优化

#8840 perf: 修改数据库应用ssl相关字段名
  apps/applications/serializers/attrs/application_category/db.py
Labels: 类型:优化

#8847 fix: 修复华为短信配置错误，前端提示不对的问题
  apps/common/sdk/sms/huawei.py
Labels: 类型:bug

#8853 feat: 支持对开启SSL/TLS的MongoDb数据库改密
  apps/common/utils/file.py
Labels: 类型:新功能

#8908 fix: 修复空字符串加密报错的问题
  apps/common/sdk/gm/piico/cipher.py
  apps/common/utils/crypto.py
Labels: 类型:bug

#8907 fix: 修复空字符串加密报错的问题
  apps/common/sdk/gm/piico/cipher.py
  apps/common/utils/crypto.py
Labels: 类型:bug
