Repository jumpserver/jumpserver, pull requests merged in 2022-12, with the labels that each got.

#9119 feat: 支持账号更新界面清空存在的秘钥信息
  apps/assets/models/base.py
  apps/assets/serializers/account/account.py
  apps/assets/serializers/base.py
Labels: 类型:新功能

#9076 perf: asyncio ws task log
  apps/ops/ws.py
  requirements/requirements.txt
Labels: 类型:优化

#9147 fix: 删除掉连接方式控制半成品代码
  apps/acls/api/connect_acl.py
  apps/acls/models/connect_acl.py
  apps/acls/serializers/connnect_acl.py
Labels: 类型:bug

#9151 fix: 删除不用migrations
  apps/acls/migrations/0008_merge_0004_connectacl_0007_auto_20221202_1048.py
Labels: 类型:bug

#9162 feat: 增加clickhouse
  apps/assets/const/database.py
  apps/assets/const/protocol.py
  apps/terminal/const.py
Labels: 类型:新功能

#9170 perf: 清理无用的依赖包
  requirements/requirements.txt
Labels: 类型:优化

#9200 perf: OpenID支持PKCE方式对接
  apps/authentication/backends/oidc/backends.py
  apps/authentication/backends/oidc/views.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/auth.py
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.po
  apps/settings/serializers/auth/oidc.py
Labels: 类型:优化

#9201 perf: OpenID支持PKCE方式对接
  apps/authentication/backends/oidc/backends.py
  apps/authentication/backends/oidc/views.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/auth.py
  apps/settings/serializers/auth/oidc.py
Labels: 类型:优化

#9212 perf: 优化启动速度
  apps/common/management/commands/services/services/base.py
  apps/common/management/commands/services/utils.py
Labels: 类型:优化

#9223 perf: 优化Sentinels配置参数
  apps/jumpserver/settings/base.py
Labels: 类型:优化
