Repository jumpserver/jumpserver, pull requests merged in 2022-03, with the labels that each got.

#7832 fix: 修复权限问题
  apps/assets/api/node.py
  apps/authentication/backends/saml2/backends.py
  apps/notifications/api/notifications.py
  apps/rbac/const.py
  apps/rbac/ztree/__init__.py
  apps/rbac/ztree/permissions.py
  apps/rbac/ztree/tree.py
  apps/rbac/ztree/tree_nodes.py
  utils/clean_db_content_types.py
Labels: 类型:bug

#7834 fix: 修复setting perm
  apps/settings/api/settings.py
Labels: 类型:bug

#7921 feat: 支持纳管百度云资产
  apps/locale/zh/LC_MESSAGES/django.po
  requirements/requirements.txt
Labels: 类型:新功能

#7800 feat: JumpServer支持部署在使用了ssl的redis上
  apps/common/cache.py
  apps/common/utils/connection.py
  apps/common/utils/lock.py
  apps/jumpserver/rewriting/session.py
  apps/jumpserver/settings/base.py
  apps/jumpserver/settings/libs.py
  utils/start_celery_beat.py
Labels: 类型:新功能

#7991 perf: 优化各种翻译
  apps/locale/ja/LC_MESSAGES/django.mo
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
  apps/settings/serializers/auth/cas.py
  apps/settings/serializers/terminal.py
Labels: 类型:优化
