Repository jumpserver/jumpserver, pull requests merged in 2022-04, with the labels that each got.

#8018 feat: 云同步支持京东云
  apps/locale/ja/LC_MESSAGES/django.mo
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.mo
  apps/locale/zh/LC_MESSAGES/django.po
Labels: 类型:新功能

#8064 perf: 优化部分云厂商的redis连接的问题
  apps/common/cache.py
  apps/jumpserver/settings/libs.py
Labels: 类型:优化

#8066 fix: 修复部署JumpServer在没有密码的redis上时，站内信数量不更新问题
  apps/jumpserver/settings/libs.py
Labels: 类型:bug

#8129 feat: 优化SAML2生成的metadata文件内容及属性映射
  apps/authentication/backends/saml2/views.py
Labels: 类型:新功能
