Repository jumpserver/jumpserver, pull requests merged in 2023-08, with the labels that each got.

#11153 Revert "perf: 锁定 Cython==0.29.35 增加 pip 选项 --use-deprecated=legacy-resolver"
  Dockerfile
  Dockerfile-ee
Labels: 类型:优化

#11174 perf: 添加清华源
  poetry.lock
Labels: 类型:优化

#11206 feat: 系统工具改为异步，增加tcpdump工具
  apps/common/utils/ip/utils.py
  apps/settings/tools/__init__.py
  apps/settings/tools/nmap.py
  apps/settings/tools/ping.py
  apps/settings/tools/tcpdump.py
  apps/settings/tools/telnet.py
  apps/settings/utils/__init__.py
  apps/settings/utils/common.py
  apps/settings/utils/nmap.py
  apps/settings/utils/telnet.py
  apps/settings/ws.py
  pyproject.toml
  requirements/requirements.txt
Labels: 类型:新功能

#11212 perf: 类型树右击可以获取节点下所有的资产
  apps/perms/api/user_permission/tree/node_with_asset.py
Labels: 类型:优化

#11210 fix: 添加华为云依赖包
  poetry.lock
  pyproject.toml
Labels: 类型:bug

#11213 perf: Dockerfile中安装nmap工具
  Dockerfile
Labels: 类型:优化

#11243 perf: 更新clients版本
  apps/templates/resource_download.html
Labels: 类型:优化

#11316 perf: 优化组件的操作行为不记录到操作日志中
  apps/audits/signal_handlers/operate_log.py
Labels: 类型:优化

#11320 fix: 操作日志判断is_service_account为匿名用户会报错
  apps/audits/signal_handlers/operate_log.py
Labels: 类型:bug

#11455 feat: telnet、ping支持批量测试
  apps/settings/tools/ping.py
  apps/settings/tools/telnet.py
  apps/settings/utils/common.py
  apps/settings/ws.py
Labels: 类型:新功能, 状态:待反馈

#11461 fix: 解决CAS无法登陆问题
  apps/jumpserver/conf.py
  apps/settings/migrations/0009_alter_cas_username_attribute.py
Labels: 类型:bug

#11452 feat: 查看/下载录像记录在操作及活动日志中
  apps/accounts/api/account/account.py
  apps/accounts/api/account/template.py
  apps/accounts/mixins.py
  apps/audits/const.py
  apps/common/api/patch.py
  apps/common/views/mixins.py
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.po
  apps/terminal/api/session/session.py
Labels: 类型:新功能, 状态:待反馈
