Repository jumpserver/jumpserver, pull requests merged in 2023-02, with the labels that each got.

#9387 fix: PrivateToken创建报错
  apps/audits/handler.py
  apps/audits/migrations/0021_alter_operatelog_resource_id.py
  apps/audits/models.py
  apps/audits/signal_handlers.py
Labels: 类型:bug

#9389 perf: 优化audits的migrations
  apps/audits/migrations/0020_auto_20230117_1004.py
  apps/audits/migrations/0021_alter_operatelog_resource_id.py
Labels: 类型:优化

#9400 fix: 解决部署后，Oracle无法执行自动化任务问题
  apps/common/management/commands/services/services/celery_base.py
Labels: 类型:bug

#9421 fix: 修复mongodb ssl账号测试失败，oracle推送用户失败问题
  apps/accounts/automations/base/manager.py
  apps/accounts/automations/change_secret/database/oracle/main.yml
Labels: 类型:bug

#9482 fix: 解决不同用户使用远程应用Navicat登录Oracle失败的问题
  apps/terminal/applets/navicat/app.py
Labels: 类型:bug

#9498 perf: 优化applet-navicat连接方式
  apps/terminal/applets/navicat/app.py
  apps/terminal/applets/navicat/const.py
Labels: 类型:优化

#9449 perf: 增加Activity日志中此资源的任务执行及详情查看
  apps/audits/api.py
  apps/audits/const.py
  apps/audits/handler.py
  apps/audits/migrations/0021_auto_20230207_0857.py
  apps/audits/models.py
  apps/audits/serializers.py
  apps/audits/signal_handlers.py
  apps/audits/signal_handlers/__init__.py
  apps/audits/signal_handlers/activity_log.py
  apps/audits/signal_handlers/login_log.py
  apps/audits/signal_handlers/operate_log.py
  apps/audits/signal_handlers/other.py
  apps/audits/tasks.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/custom.py
  apps/rbac/const.py
  apps/settings/serializers/cleaning.py
Labels: 类型:优化

#9508 perf: 优化关闭弹窗方式及数据库连接名称优化
  apps/terminal/applets/navicat/app.py
  apps/terminal/applets/navicat/const.py
Labels: 类型:优化

#9531 fix: 创建Web资产报错
  apps/common/decorators.py
Labels: 类型:bug

#9547 fix: 用户接口不分页时，api异常
  apps/users/api/user.py
Labels: 类型:bug

#9549 perf: 优化远程应用navicat连接时，确定有密码输入框后才输入密码
  apps/terminal/applets/navicat/app.py
Labels: 类型:优化

#9537 feat: 远程应用Applets支持DBeaver
  apps/terminal/applets/dbeaver/README.md
  apps/terminal/applets/dbeaver/app.py
  apps/terminal/applets/dbeaver/common.py
  apps/terminal/applets/dbeaver/i18n.yml
  apps/terminal/applets/dbeaver/icon.png
  apps/terminal/applets/dbeaver/main.py
  apps/terminal/applets/dbeaver/manifest.yml
  apps/terminal/applets/dbeaver/patch.yml
  apps/terminal/applets/dbeaver/setup.yml
Labels: 类型:新功能

#9554 perf: 优化Activity日志[操作日志、登录日志]显示
  apps/audits/api.py
  apps/audits/serializers.py
Labels: 类型:优化

#9573 fix: 解决applets在razor方式拉起代填错误问题
  apps/terminal/applets/navicat/app.py
Labels: 类型:bug

#9578 perf: 优化applets-dbeaver依赖驱动方式
  apps/terminal/applets/dbeaver/app.py
Labels: 类型:优化

#9588 fix: 解决SQLServer无法推送用户
  apps/accounts/automations/change_secret/database/sqlserver/main.yml
Labels: 类型:bug

#9592 perf: 修改PostgreSQL数据库参数为必填
  apps/assets/serializers/asset/database.py
Labels: 类型:优化

#9598 perf: 去掉dbeaver的clickhouse协议
  apps/terminal/applets/dbeaver/manifest.yml
Labels: 类型:优化

#9601 feat: 增加media权限控制
  apps/jumpserver/rewriting/storage/__init__.py
  apps/jumpserver/rewriting/storage/permissions.py
  apps/jumpserver/settings/base.py
  apps/jumpserver/urls.py
  apps/ops/models/playbook.py
  requirements/requirements.txt
Labels: 类型:新功能

#9604 fix: 远程应用图标无法显示问题
  apps/jumpserver/settings/base.py
Labels: 类型:bug

#9608 fix: 解决一些资源的Activity日志无法查看问题
  apps/audits/api.py
  apps/audits/backends/db.py
  apps/audits/handler.py
Labels: 类型:bug

#9626 fix: 解决JobLog表依赖顺序不对，导致从新迁移失败问题
  apps/audits/migrations/0021_auto_20230207_0857.py
Labels: 类型:bug

#9625 fix: 解决跨组织资源的Activty在其他组织下404的问题
  apps/audits/api.py
Labels: 类型:bug

#9627 fix: 平台Activity列表500
  apps/audits/api.py
Labels: 类型:bug

#9650 perf: Navicat为xpack功能
  apps/terminal/applets/__init__.py
  apps/terminal/models/applet/applet.py
Labels: 类型:优化

#9673 fix: 解决部分数据库在修改密码后仍能ping通的问题
  apps/accounts/automations/verify_account/database/mongodb/main.yml
  apps/accounts/automations/verify_account/database/oracle/main.yml
  apps/accounts/automations/verify_account/database/sqlserver/main.yml
Labels: 类型:bug

#9671 feat: 支持数据库在连接网域的情况下执行Task
  apps/assets/automations/base/manager.py
  apps/ops/ansible/inventory.py
  requirements/requirements.txt
Labels: 类型:新功能

#9689 fix: 操作日志、Activity日志显示当前组织和SYSTEM组织下的内容
  apps/audits/api.py
  apps/audits/signal_handlers/activity_log.py
Labels: 类型:bug

#9719 fix: 操作日志的国际化应该根据查询对象的语言决定
  apps/audits/backends/db.py
  apps/audits/serializers.py
  apps/audits/signal_handlers/operate_log.py
  apps/audits/utils.py
  apps/common/views/mixins.py
  apps/settings/serializers/settings.py
Labels: 类型:bug

#9710 fix: 创建用户和验证账号任务的Activity日志保存失败
  apps/accounts/tasks/verify_account.py
  apps/audits/signal_handlers/activity_log.py
  apps/common/tasks.py
Labels: 类型:bug

#9721 perf: 修改认证设置类的国际化，字符串方式会直接翻译成国际化内容
  apps/settings/serializers/auth/base.py
  apps/settings/serializers/auth/cas.py
  apps/settings/serializers/auth/dingtalk.py
  apps/settings/serializers/auth/feishu.py
  apps/settings/serializers/auth/ldap.py
  apps/settings/serializers/auth/oauth2.py
  apps/settings/serializers/auth/oidc.py
  apps/settings/serializers/auth/radius.py
  apps/settings/serializers/auth/saml2.py
  apps/settings/serializers/auth/sso.py
  apps/settings/serializers/auth/wecom.py
Labels: 类型:优化

#9725 fix: 对于网关无法连接的，给出原因并停止此任务的后续步骤，不影响其他任务
  apps/assets/automations/base/manager.py
Labels: 类型:bug

#9729 fix: 修复文件导出 {"": True"} 问题
  apps/assets/serializers/asset/common.py
  apps/assets/serializers/asset/host.py
  apps/common/drf/renders/base.py
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.po
Labels: 类型:bug

#9735 fix: 修复 loong64 grpc 构建失败
  Dockerfile.loong64
Labels: 类型:bug

#9736 fix: 修复 loong64 grpc 构建失败
  Dockerfile.loong64
Labels: 类型:bug

#9761 fix: 解决Activity保存因为参数出错问题
  apps/accounts/tasks/automation.py
  apps/accounts/tasks/backup_account.py
  apps/accounts/tasks/gather_accounts.py
  apps/accounts/tasks/push_account.py
  apps/assets/tasks/automation.py
  apps/common/tasks.py
  apps/ops/tasks.py
  apps/terminal/tasks.py
Labels: 类型:bug

#9759 fix: 解决Activity保存因为参数出错问题
  apps/accounts/tasks/automation.py
  apps/accounts/tasks/backup_account.py
  apps/accounts/tasks/gather_accounts.py
  apps/accounts/tasks/push_account.py
  apps/assets/tasks/automation.py
  apps/common/tasks.py
  apps/ops/tasks.py
  apps/terminal/tasks.py
Labels: 类型:bug
