Repository jumpserver/jumpserver, pull requests merged in 2023-10, with the labels that each got.

#11784 feat: 支持自定义短信认证(文件)
  apps/authentication/mfa/custom.py
  apps/common/sdk/sms/custom.py
  apps/common/sdk/sms/custom_file.py
  apps/common/sdk/sms/endpoint.py
  apps/common/utils/verify_code.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/auth.py
  apps/jumpserver/settings/custom.py
  apps/locale/ja/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/django.po
  apps/settings/api/sms.py
  apps/settings/serializers/auth/sms.py
Labels: 类型:新功能

#11767 feat: 支持LDAP用户组变更时，JS同步变更
  apps/settings/utils/ldap.py
Labels: 类型:新功能

#11902 perf: 工单直接审批者访问链接无认证跳转到登录页面
  apps/tickets/templates/tickets/approve_check_password.html
  apps/tickets/views/approve.py
Labels: 类型:优化

#11924 perf: 使用scan命令扫描在线用户
  apps/audits/models.py
Labels: 类型:优化

#11976 fix: 获取ip函数返回None
  apps/authentication/mixins.py
Labels: 类型:Bug

#11980 perf: 兼容SERVER_NAME值多种情况
  apps/jumpserver/settings/base.py
Labels: 类型:优化
