Repository jumpserver/jumpserver, pull requests merged in 2023-09, with the labels that each got.

#11474 feat: 系统工具支持traceroute
  apps/settings/tools/__init__.py
  apps/settings/tools/ping.py
  apps/settings/tools/traceroute.py
  apps/settings/utils/common.py
  apps/settings/ws.py
Labels: 类型:新功能

#11637 fix: 解决sqlserver无法推送和改密的问题
  apps/accounts/automations/change_secret/database/sqlserver/main.yml
  apps/accounts/automations/push_account/database/sqlserver/main.yml
Labels: 类型:Bug

#11644 Revert "perf: 修复 task id 不对的问题"
  apps/terminal/api/applet/host.py
Labels: 类型:优化

#11646 Revert "perf: 修复事务中任务执行"
  apps/accounts/serializers/account/account.py
  apps/accounts/tasks/push_account.py
  apps/common/decorators.py
  apps/ops/api/job.py
  apps/ops/tasks.py
  apps/terminal/api/applet/host.py
  apps/terminal/tasks.py
Labels: 类型:优化

#11680 perf: 优化找回密码时区号带加号无法匹配的问题
  apps/users/views/profile/reset.py
Labels: 类型:优化

#11679 perf: 优化找回密码时区号带加号无法匹配的问题
  apps/users/views/profile/reset.py
Labels: 类型:优化

#11704 Revert "fix: pubkey auth require svc sign"
  apps/authentication/mixins.py
  apps/common/permissions.py
Labels: 类型:Bug

#11731 perf: 更新jms-storage版本
  poetry.lock
  pyproject.toml
Labels: 类型:优化
