Repository jumpserver/jumpserver, pull requests merged in 2023-03, with the labels that each got.

#9881 perf: 邮箱测试时，不填写'主题前缀'会报错
  apps/settings/api/email.py
Labels: 类型:优化

#9882 perf: 邮箱测试时，不填写'主题前缀'会报错
  apps/settings/api/email.py
Labels: 类型:优化

#9877 fix: 操作日志显示用户加密后的密文，及日期格式调整
  apps/audits/utils.py
  apps/common/local.py
Labels: 类型:bug

#9875 fix: 操作日志显示用户加密后的密文，及日期格式调整
  apps/audits/handler.py
  apps/audits/utils.py
  apps/common/local.py
Labels: 类型:bug

#9874 fix: 操作日志显示用户加密后的密文，及日期格式调整
  apps/audits/handler.py
  apps/audits/utils.py
  apps/common/local.py
Labels: 类型:bug

#9898 fix: 操作日志可能保存明文密码
  apps/common/local.py
Labels: 类型:bug

#9897 fix: 操作日志有可能保存明文密码
  apps/common/local.py
Labels: 类型:bug

#9916 feat: 支持飞书国际版(lark)
  apps/authentication/views/feishu.py
  apps/common/sdk/im/feishu/__init__.py
  apps/jumpserver/conf.py
  apps/jumpserver/settings/auth.py
  apps/settings/serializers/auth/feishu.py
Labels: 类型:新功能
