Repository jumpserver/jumpserver, pull requests merged in 2024-04, with the labels that each got.

#12956 Revert "feat: 支持中文繁体"
  apps/locale/zh/LC_MESSAGES/django.po
  apps/locale/zh/LC_MESSAGES/djangojs.po
Labels: 类型:新功能

#13042 fix: 【账号改密】任务列表-详情：获取任务记录tab报错
  apps/accounts/filters.py
Labels: 类型:Bug

#13081 perf: 优化频繁发送短信，将后端的频繁发送警告提示到页面上来提醒用户
  apps/authentication/api/mfa.py
  apps/common/utils/verify_code.py
  apps/templates/_mfa_login_field.html
Labels: 类型:优化

#13105 perf: 优化会话过期500问题
  apps/authentication/api/mfa.py
  apps/templates/_mfa_login_field.html
Labels: 类型:优化

#13103 perf: 优化 Web 资产详情时根据 autofill 类型返回对应的 spec_info 信息
  apps/assets/serializers/asset/info/spec.py
Labels: 类型:优化

#13104 perf: 优化会话过期500问题
  apps/authentication/api/mfa.py
  apps/templates/_mfa_login_field.html
Labels: 类型:优化

#13100 feat: 修改 receptor 容器通信地址
  apps/jumpserver/conf.py
Labels: 类型:新功能

#13145 Revert "perf: remove ticket feature"
  apps/acls/serializers/base.py
  apps/authentication/urls/api_urls.py
  apps/jumpserver/settings/custom.py
  apps/settings/serializers/feature.py
  apps/tickets/urls/api_urls.py
  apps/tickets/urls/view_urls.py
Labels: 类型:新功能
